# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/usr/sbin:/sbin

PATH=$PATH:$HOME/hadoop/bin:$HOME/hadoop/sbin

export PATH

export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/

alias sl='ls'
alias vi='vim'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias d:="cd /cygdrive/d"
alias c:="cd /cygdrive/c"
alias sys:="cd /cygdrive/c"
alias app:="cd /cygdrive/d"
alias liuy:="cd /cygdrive/c/Users/liuy"
alias lab:="cd /cygdrive/e"
alias cor:="cd /cygdrive/f"
alias my:="cd /cygdrive/g"
alias prv:="cd /cygdrive/h"
alias dat:="cd /cygdrive/i"
alias lt="ls -l -t"
alias ls='ls --show-control-chars --color'
alias dir='dir -N --color'
alias sync='rsync -v -P -e ssh -C '
alias emacsnw="emacs -nw"

export GREP_OPTIONS='--color=auto'

export TERM=xterm-256color

#keychain ~/.ssh/id_rsa
#keychain ~/.ssh/id_rsa.github
#source ~/.keychain/Jade-sh

source ~/.bashrc
