#! /usr/bin/env python
# -*- coding: utf-8 -*-

lst = [('➙', 'Heavy Rightwards'),
       ('➢', ''),
       ('➣', ''),
       ('➤', 'Black Rightwards arrow head'),
       ('⬅', 'Leftwards black arrow'),
       ('➡', 'Black Rightwards arrow'),
       ('➳', ''),
       ('➵', ''),
       ('➸', 'Heavy Black Feathered'),
       ('➼', 'Wedge-Tailed Rightwards Arrow'),
       ('➽', 'Heavy Wedge-Tailed Rightwards Arrow'),
       ('⦁', 'Z Notation Spot'),
       ('⚳', ''),
       ('☻', 'Black Smiling Face'),
       ('☺', 'White Smiling Face'),
       ('☹', 'Whilte Frowning Face'),
       ('❖', 'BLACK DIAMOND MINUS WHITE X'),
       ('✪', ''),
       ('•', 'jia zhong hao'),
       ('‣', 'san jiao jia zhong hao'),
       ('‥', 'two dot qian zhao hao'),
       ('‹›', 'zhi jian yin hao'),
       ('❮❯'),
       ('⟨⟩'),
       ('∙', 'dot calcation'),
       ('·', 'another dot'),
       ('º', 'Masculine ordinal indicator'),
       ('°', 'degree symbol'),
       ('⌃⌄', 'up/down arrow head'),
       ('☑☒', ''),
       ('♯'),
       ('⛶', '26f6'),
       ('⛝', '26dd'),
       ('࿕'),
       ('ᗅ'),
       ('∆∇', 'increament, nabla'),
       ('∧∨', 'logical and or'),
       ('⋎⋏', 'curly logical and or'),
       ('⏫⏬⏪⏩', 'U+23e9'),
       ('»'),
       ('✖✕'),
       ('✚'),
       ('∑−∓¯'),
       ('➕➖'),
       ('│'),
       ('≠≈'),
       ('¬', 'NOT'),
       ('⮠↲', 'return'),
       ('∽', 'function'),
       ('⇒⇔', 'function'),
       ('∃', 'exist'),
       ('ℳ', 'm'),
       ('ℱ', 'f'),
       ('ℰ', 'E'),
       ('ℍ', 'H'),
       ('ℏ', 'h'),
       ('₳₣'),
       (''),
       ]
for e in lst:
    for i in e:
        print i,
    print
