export BRAZIL_WORKSPACE_DEFAULT_LAYOUT=short

export AUTO_TITLE_SCREENS="NO"

# if you wish to use IMDS set AWS_EC2_METADATA_DISABLED=false
export AWS_EC2_METADATA_DISABLED=true

export PROMPT="
%{$fg[white]%}(%D %*) <%?> [%~] $program %{$fg[default]%}
%{$fg[cyan]%}%m %#%{$fg[default]%} "

export RPROMPT=

set-title() {
    echo -e "\e]0;$*\007"
}

ssh() {
    set-title $*;
    /usr/bin/ssh -2 $*;
    set-title $HOST;
}

alias e=emacs
alias bb=brazil-build

alias bba='brazil-build apollo-pkg'
alias bre='brazil-runtime-exec'
alias brc='brazil-recursive-cmd'
alias bws='brazil ws'
alias bwsuse='bws use -p'
alias bwscreate='bws create -n'
alias brc=brazil-recursive-cmd
alias bbr='brc brazil-build'
alias bball='brc --allPackages'
alias bbb='brc --allPackages brazil-build'
alias bbra='bbr apollo-pkg'


export PATH=$HOME/.toolbox/bin:$PATH

# Set up rtx for runtime management
# active python3 (otherwise, it's python2), repo need this
[ -f "$HOME/.local/share/rtx/bin/rtx" ] && eval "$(/home/lyz/.local/share/rtx/bin/rtx activate zsh)"
# source ~/.local/share/rtx/completions.zsh
### SLOW, real pain point
# source /home/lyz/.brazil_completion/zsh_completion
### AMZ insert

### YANG
TZ='Asia/Shanghai'; export TZ
# autojump
[ -f ~/.zoxide.zsh ] && source ~/.zoxide.zsh

# history search
# FZF support this function
# export MCFLY_FUZZY=2
# export MCFLY_INTERFACE_VIEW=BOTTOM
# eval "$(mcfly init zsh)"
# zmodload zsh/zprof
# Kiro CLI pre block. Keep at the top of this file.
# [[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"
# Amazon Q pre block. Keep at the top of this file.
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"
### for debug
# gdate +"%T.%3N"
# set -x
### END for debug 

# enable light mode with this global env, to contorl tmux/vim/mcfly
export YTHEME=dark

# BT101 introduce in zsh
# export PATH=$PATH:/Users/lyz/.toolbox/bin
eval "$(/opt/homebrew/bin/brew shellenv)"
# Set up rtx for runtime management
# eval "$(rtx activate zsh)"
# rtx is renamed to mise
# Aug-20, shell PROMPT is blocked by misc
# eval "$(mise activate zsh)"

export PATH=$HOME/.local/bin/:$HOME/.toolbox/bin:$PATH

# Path to your oh-my-zsh installation.
# echo $PATH | grep -i 'R/bin'
ZSH=$HOME/.oh-my-zsh

ZSH_THEME=myagnoster
ZSH_THEME=fast-agnoster
[[ -f ~/.zsh_local ]] && source ~/.zsh_local
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

### quickly switch directory (autojump -> z -> zoxide)
## autojump
# [[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh

## z
# _ZL_CMD=j
# _ZL_ECHO=1
# _ZL_MATCH_MODE=1
# [[ -f ~/git/pub/z.lua/z.lua ]] && eval "$(lua53 ~/git/pub/z.lua/z.lua --init zsh once)"

## zoxide, rust sponsored, I think it's better performance
[ -f ~/.zoxide.zsh ] && source ~/.zoxide.zsh

# fasd      fast switch directory, list recent files
# vi-mode
# zsh-syntax-highlighting       highlight command when input it.
# zaw       fuzzy history search
plugins=(fasd vi-mode fast-syntax-highlighting pip cabal)

[[ -f $ZSH/oh-my-zsh.sh ]] && source $ZSH/oh-my-zsh.sh
unsetopt correct
unsetopt correct_all

# User configuration

if command -v gdircolors >/dev/null 2>&1; then
    [[ -f ~/.dircolors ]] && eval "$(gdircolors -b ~/.dircolors)"
    alias ls='gls --color=auto'
else
    [[ -f ~/.dircolors ]] && eval `dircolors ~/.dircolors`
fi

# Make all GNU flavor commands available, may override same-name BSD flavor commands
# For M1 Mac
# Make (new version)
export PATH="/opt/homebrew/opt/make/libexec/gnubin/:/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:${MANPATH}"
# mac/freebsd doesn't support dircolors
# set dircolors colorful completion
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# export MANPATH="/usr/local/man:$MANPATH"

#PATH=/mnt/fileroot2/yang.liu/hifi4/RI-2019.2-linux/XtensaTools/bin::$PATH
#PATH=/opt/xtensa/XtDevTools/install/tools/RI-2019.2-linux/XtensaTools/bin/:$PATH
#XTENSA_CORE=AmlHifi4_v3
#XTENSA_SYSTEM=/mnt/fileroot2/yang.liu/hifi4/RI-2019.2-linux/AmlHifi4_v3/config/
#XTENSA_CORE=Amlogic_v3
#XTENSA_SYSTEM=/opt/xtensa/XtDevTools/install/builds/RI-2019.2-linux/Amlogic_v3/config/
#XTENSA_SYSTEM=/mnt/fileroot2/yang.liu/hifi4/RI-2019.2-linux/Amlogic_v3/config/

# PATH=/opt/gcc-linaro-7.3.1-2018.05-x86_64_armv8l-linux-gnueabihf/bin:/opt/gcc-linaro-aarch64-none-elf-4.9-2014.09_linux/bin:$PATH
# XTENSA_CORE=
# XTENSA_SYSTEM=
#PATH=$PATH:$HOME/.local/bin:$HOME/.cabal/bin
#PATH=$PATH:$HOME/.gem/ruby/2.2.0/bin

#LM_LICENSE_FILE=/home/yang.liu/tmp.lic #:$LM_LICENSE_FILE
#LM_LICENSE_FILE=/home/yang.liu/T/license.droid11.lic #:$LM_LICENSE_FILE

[[ -f ~/.aliases ]] && source ~/.aliases

ulimit -c unlimited

# export CCACHE_DIR=$HOME/.ccache
export XDG_CACHE_HOME=/tmp/xdgcache

# make colorful MAN output
export LESS_TERMCAP_mb=$'\E[01;31m' # begin blinking
export LESS_TERMCAP_md=$'\E[01;31m' # begin bold
export LESS_TERMCAP_me=$'\E[0m' # end mode
export LESS_TERMCAP_se=$'\E[0m' # end standout-mode
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin standout-odeinfobox
export LESS_TERMCAP_ue=$'\E[0m' # end underline
export LESS_TERMCAP_us=$'\E[01;32m' # begin underline
# make less support UTF-8, to avoid mosaic char
export LESSCHARSET=UTF-8

export EDITOR='vim'
# crontab need this.
export VISUAL='vim'
bindkey -v
set -o vi
# enter ESC key, lag 0.1 seconds (default 0.4 seconds)
export KEYTIMEOUT=1

# GTK_IM_MODULE=xim, XMODIFIERS=fcitx to suport fcitx @ chrome
export XMODIFIERS='@im=fcitx'
export XIM=fcitx
export XIM_PROGRAM=fcitx
export QT_IM_MODULE="fcitx"
export GTK_IM_MODULE=xim

# export LANGUAGE=

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
#export LANG="zh_CN.UTF8"
#export LC_ALL="zh_CN.UTF8"
export LC_CTYPE="en_US.UTF-8"

# bindkey '^R' history-incremental-search-backward
# default bind key for zaw
bindkey '^R' zaw-history
# default bind key for zaw
# ^N         down-line-or-history
# ^P         up-line-or-history
zstyle ':filter-select' extended-search yes
# zle -N u
# bindkey "^F" u
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward
# as page up page down
bindkey '\e[5~' history-search-backward
bindkey '\e[6~' history-search-forward
bindkey "\e[3~" delete-char
# VT
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
#
# # kvt
# bindkey "\e[H" beginning-of-line
# bindkey "\e[F" end-of-line
#
# # rxvt and konsole (i.e. the KDE-app...)
# bindkey "\e[7~" beginning-of-line
# bindkey "\e[8~" end-of-line

# VT220
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]"  history-search-backward
bindkey "$terminfo[kcud1]"  history-search-forward
bindkey -M vicmd 'k'        history-search-backward
bindkey -M vicmd 'j'        history-search-forward
set completion-ignore-case on

export HISTCONTROL=erasedups
export HISTSIZE=10000
export HISTIGNORE="cd(| *):(ls|dir)(| *):(rm|mv|cp|ln|scp|rmdir|mkdir) *:(echo|print)(| *):(g|)vim(| *):vi:vi *:e *:cat(| *):man *:(which|whence|type)(| *)|[fb]g(| *):feh *:pwd:exit(| *):date:kill(| *):ping *:ssh *:clear *:sleep *:history:tail *:head *:z *"
export SAVEHIST=1000
export HISTFILE=~/.zsh_history
#unsetopt INC_APPEND_HISTORY
setopt INC_APPEND_HISTORY
#setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_NO_FUNCTIONS
setopt HIST_IGNORE_SPACE
# unset hist_verify to instant get last command by !!
#setopt hist_verify
unsetopt hist_verify

# directory stack
# dirs -v
# print directory stack
#
# enter number to skip in directory stack
#
# cd -TAB, will list directory stack
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS

setopt AUTO_LIST
setopt AUTO_MENU

setopt nolistambiguous

setopt interactivecomments

unset GNOME_KEYRING_CONTROL

settitle() {
    if [[ $TERM == "screen-256color" ]]; then
        printf "\033k$1\033\\"
    fi
}

# settitle "untitled"

export CLASSPATH=.:$HOME/.local/framework:$CLASSPATH

# on my urxvt it works with <alt>-<left>/-<right>
bindkey "\e\e[D" backward-word
bindkey "\e\e[C" forward-word

loadPlugin() {
    [[ -z "$1" ]] && source "$1"
}

loadPlugin "$HOME/.oh-my-zsh/custom/plugins/hub"
loadPlugin "$HOME/.oh-my-zsh/custom/plugins/vimcmd.sh"

### make ctrl-z will return to vim
# first in vim, ctrl-z will put vim background, so we return to shell
# then in shell, ctrl-z will find background vim, so we return to vim
# Issue:
# This binding make cannot put second process to background
# Ref: http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# vim readline binding C-j to newline. I don't like it.
# It break vim-tmux-navigator binding
bindkey -r '^j'
function select_down_pane() {
    tmux select-pane -D
}
zle -N select_down_pane
bindkey ^j 'select_down_pane'

export CHEATCOLORS=true

export FZF_DEFAULT_OPTS='--height 90% --layout=reverse --border'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# History search
# config 2-5
if [[ $YTHEME == "light" ]]; then
    export MCFLY_LIGHT=TRUE
else
    export MCFLY_LIGHT=FALSE
fi
export MCFLY_FUZZY=2
export MCFLY_INTERFACE_VIEW=BOTTOM
export MCFLY_RESULTS_SORT=LAST_RUN
eval "$(mcfly init zsh)"

autoload -U colors && colors
if [[ $YTHEME == "light" ]]; then
    precmd() { print -rP "%{$fg[black]%}%~" }
elif [[ $YTHEME == "dark" ]]; then
    precmd() { print -rP "%{$fg[green]%}%~ %{$fg[blue]%}<$SUBJECT> " }
else
    precmd() { print -rP "%{$fg[white]%}%~" }
fi
SUBJECT=nil
# export PROMPT="%# "
export PROMPT="%{$fg[red]%}\\%{$reset_color%} "
# rtx may crash with this ISO-8859 char, move to UTF-8 could workaround this issue

### for debug
# echo "zshrc load"
# gdate +"%T.%3N"
### END for debug

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# zshrc Updates to point to Pyenv shims. keep this for python env
export PATH=$HOME/.pyenv/shims:$PATH
# temp for dots kats agent
# export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
# export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
# export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
# export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"

# export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

gg() {
    python3 /Users/lyz/.gg/gg.py "$@"
    if [ "$1" = "load" ]; then
        if [ -f /Users/lyz/.gg/load_command.txt ]; then
            cmd=$(cat /Users/lyz/.gg/load_command.txt)
            if [[ "$SHELL" == */bash ]]; then
                history -s "$cmd"
                echo "$cmd"
            elif [[ "$SHELL" == */zsh ]]; then
                print -z "$cmd"
            else
                echo "Unsupported shell. Please copy the command manually:"
                echo "$cmd"
            fi
        fi
    fi
}


    autoload -Uz compinit
    compinit

    _gg_completion() {
        local -a commands
        commands=(
            "list:List all patterns"
            "view:View a specific pattern"
            "edit:Edit a specific pattern"
            "add:Add a new pattern"
            "load:Load a pattern's command for editing"
            "lint:Lint all pattern files"
            "stats:Show pattern statistics"
            "help:Show help message"
        )

        _arguments -C \
            "1: :->command" \
            "*::arg:->args"

        case $state in
            command)
                _describe "command" commands
                ;;
            args)
                case $words[1] in
                    view|edit|load)
                        _values "patterns" $(gg list)
                        ;;
                    add)
                        _values "modules" $(ls /Users/lyz/.gg/patterns_personal /Users/lyz/.gg/patterns_central | sed 's/\.txt$//')
                        ;;
                esac
                ;;
        esac
    }

    compdef _gg_completion gg
    

. "$HOME/.local/bin/env"

#export JAVA_HOME=$(/usr/libexec/java_home)
export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/

# Amazon Q post block. Keep at the bottom of this file.
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"

export MODELSCOPE_CACHE=$HOME/.cache/modelscope
export QUIP_API_TOKEN="QlhIOU1BQ0RiOHk=|1793873815|Upb4JFMBtlmYZgMMudEWcQTL8rqo2Sdh+woqjT9B6UA="

# Kiro CLI post block. Keep at the bottom of this file.
# [[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
